### ISSUE TITLE
[Ansible] Error with requirements and TensorFlow

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/donkeycarLPH#48]
Error [found by testing](https://github.com/mdl29/donkeycarLPH/pull/39#issuecomment-1103036752) #39 that may be also present here and should be fixed for the service to work well.

## python manage.py drive --js issue 

I noticed 2 errors : 
- A missing dependency, I have attached a pip freeze ( [pipFreezeDs4Drv.txt](https://github.com/mdl29/donkeycarLPH/files/8516072/pipFreezeDs4Drv.txt) ) for further investigation we should compare it to dababycar ( [dababycarPipFreeze.txt](https://github.com/mdl29/donkeycarLPH/files/8516158/dababycarPipFreeze.txt) )

```
venv) pi@bluecar:~/mycar $ python manage.py drive --js
python: can't open file 'manage.py': [Errno 13] Permission denied
(venv) pi@bluecar:~/mycar $ ^Cthon manage.py drive --js
(venv) pi@bluecar:~/mycar $ sudo chown -R .
chown: missing operand after ‘.’
Try 'chown --help' for more information.
(venv) pi@bluecar:~/mycar $ ls -lisha
total 124K
254250 4.0K drwxr-xr-x 5 root root 4.0K Apr 19  2022 .
   825 4.0K drwxr-xr-x 6 pi   pi   4.0K Dec  2 02:36 ..
254257 8.0K -rwx------ 1 root root 4.8K Apr 19  2022 calibrate.py
254255  32K -rw-r--r-- 1 root root  32K Apr 19  2022 config.py
254252 4.0K drwxr-xr-x 2 root root 4.0K Apr 19  2022 data
254253 4.0K drwxr-xr-x 2 root root 4.0K Apr 19  2022 logs
254254  40K -rwx------ 1 root root  37K Apr 19  2022 manage.py
254251 4.0K drwxr-xr-x 2 root root 4.0K Apr 19  2022 models
 14107  20K -rw-r--r-- 1 root root  17K Apr 19  2022 myconfig.py
254256 4.0K -rwx------ 1 root root  728 Apr 19  2022 train.py
(venv) pi@bluecar:~/mycar $ sudo chown -R pi:pi .
(venv) pi@bluecar:~/mycar $ python manage.py drive --js
________             ______                   _________              
___  __ \_______________  /___________  __    __  ____/_____ ________
__  / / /  __ \_  __ \_  //_/  _ \_  / / /    _  /    _  __ `/_  ___/
_  /_/ // /_/ /  / / /  ,<  /  __/  /_/ /     / /___  / /_/ /_  /    
/_____/ \____//_/ /_//_/|_| \___/_\__, /      \____/  \__,_/ /_/     
                                 /____/                              

using donkey v4.3.10 ...
WARNING:donkeycar.parts.pins:pigpio was not imported.
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    from donkeycar.parts.datastore import TubHandler
  File "/home/pi/projects/donkeycar/parts/datastore.py", line 19, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

Can someone compare those 2 pip freeze @yannis-mlgrn @viandoxdev  : 
- [pipFreezeDs4Drv.txt](https://github.com/mdl29/donkeycarLPH/files/8516072/pipFreezeDs4Drv.txt) )
- [dababycarPipFreeze.txt](https://github.com/mdl29/donkeycarLPH/files/8516158/dababycarPipFreeze.txt) )

TensorFlow seems wrong (not de local version) and they are a lot of differences, don't forget that dababycar might have useless packages also. We might need several tests.

**Comment by yannis-mlgrn** [comment]
# TASKS : 
- [ ] compare these files
- [ ] Search why TensorFlow seems wrong

**Comment by yannis-mlgrn** [comment]
In [pipFreezeDs4Drv.txt](https://github.com/mdl29/donkeycarLPH/files/8516072/pipFreezeDs4Drv.txt) , requirements are more recent that in [dababycarPipFreeze.txt](https://github.com/mdl29/donkeycarLPH/files/8516158/dababycarPipFreeze.txt). I think because the installation was made 2~4 month after dababycar. Moroever the TensorFlow versions and modules are not the same in these files : 

**Dababycar :**
```
tensorboard==2.2.2
tensorboard-plugin-wit==1.8.0
tensorflow @ file:///home/pi/projects/donkeycar/tensorflow-2.2.0-cp37-cp37m-linux_armv7l.whl
tensorflow-estimator==2.2.0
```  
**Packer-image :**
```
tensorboard==2.2.2
tensorboard-plugin-wit==1.8.1
tensorflow==2.2.0
tensorflow-estimator==2.2.0
```
## Packages differences in Packer image :
```diff
+ adafruit-circuitpython-typing==1.4.0
- asn1crypto==0.24.0
- beautifulsoup4==4.7.1
- cached-property==1.5.2
- chardet==3.0.4
+ charset-normalizer==2.0.12
- cryptography==2.6.1
- -e git+https://github.com/Benvii/ds4drv@f6b6259241ec2bf21fbbe915487b77c3174caa9c#egg=ds4drv
+ ds4drv==0.5.1
- entrypoints==0.3
- html5lib==1.0.1
+ imageio==2.17.0
+ imgaug==0.4.0
- keyring==17.1.1
- keyrings.alt==3.1.1
- lxml==4.3.2
- numexpr==2.6.9
+ networkx==2.6.3
+ opencv-python==4.5.5.64
- olefile==0.46
+ packaging==21.3
- pandas==0.23.3+dfsg
- pigpio==1.78

**Comment by yannis-mlgrn** [comment]
For install : 
 - pigpio : `pip install pigpio` | install pigpio==1.78
 - virtualenv : `pip install virtualenv` | install many packages who explain why we have more packages in dababycar requirements.txt .
   Packages installed : 
    ```
    distlib==0.3.4
    filelock==3.6.0
    importlib-metadata==4.11.3
    pkg-resources==0.0.0
    platformdirs==2.5.2
    six==1.16.0
    typing-extensions==4.2.0
    virtualenv==20.14.1
    zipp==3.8.0
    ```

**Comment by yannis-mlgrn** [comment]
I have an idea that pigpio was not installed on the raspberry pi. Because we create empty environment after installing pigpiod with apt command. Pigpio is therefore missing in our py env. Maybe it's the same process for pandas.
